// This file is auto-generated by schema-bridge

export type MyStruct = { name: string; age: number; is_active: boolean; tags: string[]; meta: string | null; };

export type MyEnum = 'OptionA' | 'OptionB';

export type UserId = string;

export type ExternalStatus = 'Active' | 'Inactive';

export type AppStatus = 'Active' | 'Inactive';

